version: 2
sources:
  - name: meteo_france_quot
    tables:
      - name: rr_t_vent
        config:
          external_location: "../dataset/meteo_france_quot/data/*RR-T-Vent.parquet"
      - name: autres_parametres
        config:
          external_location: "../dataset/meteo_france_quot/data/*autres-parametres.parquet"
  # - name: meteo_france_hor
  #   tables:
  #     - name: data
  #       config:
  #         external_location: "../dataset/meteo_france_hor/data/*.parquet"